export enum CryptoCode {
  BTC = 'BTC',
  BCH = 'BCH',
  DASH = 'DASH',
  ETH = 'ETH',
  LTC = 'LTC',
  ZEC = 'ZEC',
  USDT = 'USDT',
  USDC = 'USDC',
  XMR = 'XMR',
  TRX = 'TRX',
  USDT_TRON = 'USDT_TRON',
  LN = 'LN',
}

export const COINS = CryptoCode /* Keep COINS for backwards compat */

const CRYPTOS = [
  {
    cryptoCode: CryptoCode.BTC,
    display: 'Bitcoin',
    displayCode: 'BTC',
    code: 'bitcoin',
    configFile: 'bitcoin.conf',
    daemon: 'bitcoind',
    defaultPort: 8332,
    unitScale: 8,
    zeroConf: true,
    type: 'coin',
    prefixRequired: false,
    urlPrefix: 'bitcoin',
    urlAmount: 'amount',
  },
  {
    cryptoCode: CryptoCode.BCH,
    display: 'Bitcoin Cash',
    displayCode: 'BCH',
    code: 'bitcoincash',
    configFile: 'bitcoincash.conf',
    daemon: 'bitcoincashd',
    defaultPort: 8336,
    unitScale: 8,
    zeroConf: true,
    type: 'coin',
    prefixRequired: true,
    urlPrefix: null,
    urlAmount: 'amount',
  },
  {
    cryptoCode: CryptoCode.DASH,
    display: 'Dash',
    displayCode: 'DASH',
    code: 'dash',
    configFile: 'dash.conf',
    daemon: 'dashd',
    defaultPort: 9998,
    unitScale: 8,
    zeroConf: true,
    type: 'coin',
    prefixRequired: false,
    urlPrefix: 'dash',
    urlAmount: 'amount',
  },
  {
    cryptoCode: CryptoCode.ETH,
    display: 'Ethereum',
    displayCode: 'ETH',
    code: 'ethereum',
    configFile: 'geth.conf',
    daemon: 'geth',
    defaultPort: 8545,
    unitScale: 18,
    zeroConf: false,
    hideFromInstall: true,
    type: 'coin',
    prefixRequired: false,
    urlPrefix: 'ethereum',
    urlAmount: 'amount',
  },
  {
    cryptoCode: CryptoCode.TRX,
    display: 'Tron',
    displayCode: 'TRX',
    code: 'tron',
    unitScale: 6,
    zeroConf: false,
    hideFromInstall: true,
    type: 'coin',
    prefixRequired: false,
    urlPrefix: 'tron',
    urlAmount: 'amount',
  },
  {
    cryptoCode: CryptoCode.USDT_TRON,
    cryptoCodeDisplay: 'USDT (Tron)',
    display: 'USDT (Tron)',
    displayCode: 'USDT (Tron)',
    code: 'tether_tron',
    unitScale: 6,
    zeroConf: false,
    hideFromInstall: true,
    contractAddress: 'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t',
    testnetContractAddress: 'TG3XXyExBkPp9nzdajDZsozEu4BkaSJozs',
    type: 'trc-20',
    isCashinOnly: true,
    urlPrefix: 'tron',
    prefixRequired: false,
    urlAmount: 'amount',
    validatorKey: 'TRX',
  },
  {
    cryptoCode: CryptoCode.LTC,
    display: 'Litecoin',
    displayCode: 'LTC',
    code: 'litecoin',
    configFile: 'litecoin.conf',
    daemon: 'litecoind',
    defaultPort: 9332,
    unitScale: 8,
    zeroConf: true,
    type: 'coin',
    prefixRequired: false,
    urlPrefix: 'litecoin',
    urlAmount: 'amount',
  },
  {
    cryptoCode: CryptoCode.USDT,
    display: 'USDT',
    displayCode: 'USDT',
    code: 'tether',
    unitScale: 6,
    contractAddress: '0xdac17f958d2ee523a2206206994597c13d831ec7',
    type: 'erc-20',
    zeroConf: false,
    hideFromInstall: true,
    isCashinOnly: true,
    prefixRequired: false,
    urlPrefix: 'ethereum',
    urlAmount: 'amount',
    validatorKey: 'ETH',
  },
  {
    cryptoCode: CryptoCode.USDC,
    display: 'USDC',
    displayCode: 'USDC',
    code: 'usdc',
    unitScale: 6,
    contractAddress: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
    type: 'erc-20',
    zeroConf: false,
    hideFromInstall: true,
    isCashinOnly: true,
    prefixRequired: false,
    urlPrefix: 'ethereum',
    urlAmount: 'amount',
    validatorKey: 'ETH',
  },
  {
    cryptoCode: CryptoCode.XMR,
    display: 'Monero',
    displayCode: 'XMR',
    code: 'monero',
    configFile: 'monero.conf',
    daemon: 'monerod',
    wallet: 'monero-wallet-rpc',
    defaultPort: 18081,
    walletPort: 18082,
    unitScale: 12,
    zeroConf: true,
    type: 'coin',
    prefixRequired: false,
    urlPrefix: 'monero',
    urlAmount: 'amount',
  },
  {
    cryptoCode: CryptoCode.ZEC,
    display: 'Zcash',
    displayCode: 'ZEC',
    code: 'zcash',
    configFile: 'zcash.conf',
    daemon: 'zcashd',
    defaultPort: 8232,
    unitScale: 8,
    zeroConf: true,
    hideFromInstall: true,
    type: 'coin',
    prefixRequired: false,
    urlPrefix: 'zcash',
    urlAmount: 'amount',
  },
  {
    cryptoCode: CryptoCode.LN,
    display: 'Lightning Network',
    displayCode: 'BTC',
    code: 'ln',
    configFile: null,
    daemon: null,
    defaultPort: null,
    unitScale: 8,
    zeroConf: true,
    hideFromInstall: true,
    type: 'coin',
    prefixRequired: false,
    urlPrefix: null,
    validatorKey: 'disabled',
  },
]

export const CRYPTO_CURRENCIES = [...CRYPTOS].sort((a, b) => {
  const codeCompare = a.code.localeCompare(b.code);
  if (codeCompare !== 0) return codeCompare;
  return a.cryptoCode.localeCompare(b.cryptoCode);
});

export const ALL_CRYPTOS = Object.values(CryptoCode);
